/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (BreathOfFire3)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8014AA0Cu
#define func_8014AA0C BootEntry  /* alias */
