/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (BreathOfFire3Recomp)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8014AA0Cu
#define func_8014AA0C BootEntry  /* alias */

/* guessed: wtrace battlebegin.json 2026-09-05: writes the actor present flag C+0 1 804 times (unchanged) across field and battle -- the per-actor frame task; 2420 B, 8 callees (largest boot function by insns after the text engine) */
#define PSX_FN_Actor_Task 0x8014C3C8u
#define func_8014C3C8 Actor_Task  /* alias */

/* guessed: wtrace battlebegin.json 2026-09-05: 10 824 writes over a whole battle to actor C+0x2E/+0x30/+0x32/+0x60 (every frame, every slot); ghidra: computes +0x32 from +0x36/+0x3A/+0x34/+0x38 minus camera 0x8014931C/1E and a per-sprite table at 0x8017FED4[+0x2B*3] -- world->screen projection of the party actor */
#define PSX_FN_Actor_UpdateScreenPos 0x8014D184u
#define func_8014D184 Actor_UpdateScreenPos  /* alias */

/* guessed: wtrace battlebegin.json 2026-09-05: writes C+0x4A/+0x58 every ~2 frames per slot (1 622 changing writes); siblings 0x8014DA8C (+0x4A/+0x58/+0x5A) and 0x8014D9E0 (+0x4A) -- sprite animation counters */
#define PSX_FN_Actor_AnimTick 0x8014D86Cu
#define func_8014D86C Actor_AnimTick  /* alias */

/* confirmed: Flag_Test(bits, index) -> (bits[index>>3] >> (index&7)) & 1 -- eight instructions, read from the disc EXE 2026-09-05 (tools/disasm_exe.py 8015BFC4:8); 0x8015BFE4 is the matching xor toggle. Save_BuildImage calls it as (0x80144F24, 0x92) and stores the BIT in the slot-summary byte 0x80145588 -- it was named Save_FlagsChecksum ('hash over 0x92 bytes') until tools/save_tool.py verify checked the byte against the flag array on all three card1 saves */
#define PSX_FN_Flag_Test 0x8015BFC4u
#define func_8015BFC4 Flag_Test  /* alias */

/* confirmed: wtrace levelup3.json 2026-09-05 + ghidra: (rec) copies base stats rec+0x3C..0x58 -> effective rec+0x1C..0x38, applies FUN_80166150/801662CC/8016651C/80165290 (equipment/modifiers via Stat_AddClamped), scales effective max HP rec+0x1C by (base * u8 rec+0x1A + 5)/10 and clamps HP rec+0x14, halves rec+0x2B..0x33 per status bits in rec+0x19, per-roster table 0x80148668 (5 B) vs rec+0x34..0x38; proves the persistent character records are &0x80144964 + roster*0xA4, 8 of them */
#define PSX_FN_Char_RecalcStats 0x80165434u
#define func_80165434 Char_RecalcStats  /* alias */

/* confirmed: shop buy trace buy.json 2026-09-05 (SHOP.EMI 0x801D1E98 jal, a0=item id byte 0x801E5F7C, a1=qty) + ghidra: (category, item_id, count): id list = *(0x801C9934 + cat*4), count list = *(0x801C9948 + cat*4), 128 slots; existing stack += count (cap 99, returns 0 when capped) else first slot with id 0 or count 0; scratchpad 0x1F800000 = 1 if a new slot was used */
#define PSX_FN_Inventory_Add 0x80165AA4u
#define func_80165AA4 Inventory_Add  /* alias */

/* guessed: wtrace levelup3.json 2026-09-05: wrote 0x5E into the first zero byte at rec+0x71 (Teepo, level 3->4); ghidra: (id, p2, use_global, p4) stores id in the first free slot of a 10-slot list from FUN_80167514(p2,id,p4) or the 128-slot list at 0x80145468 (NOT the inventory -- see Inventory_Add) */
#define PSX_FN_AbilityList_Add 0x80165BCCu
#define func_80165BCC AbilityList_Add  /* alias */

/* confirmed: wtrace levelup3.json 2026-09-05 + ghidra: (u16* stat, s16 delta) adds with floor 0 and cap 999, returns the applied delta; called from the equipment modifier pass under Char_RecalcStats */
#define PSX_FN_Stat_AddClamped 0x80165EE4u
#define func_80165EE4 Stat_AddClamped  /* alias */

/* confirmed: equip3.json 2026-09-05: on weapon swap (record +0x0E 3->0x1C) START.EMI 0x801D6E70 calls it with (count ptr 0x801452CA, item 0x1C, 1, id ptr 0x801450CA) and the count went 2->1 at store pc 0x80166F94; then Inventory_Add(1, 3, 1) put the old weapon back (slot 5) and the menu wrote the record byte at 0x801D6EA4 */
#define PSX_FN_Inventory_Remove 0x80166F30u
#define func_80166F30 Inventory_Remove  /* alias */

/* confirmed: ghidra 2026-09-05: (amount) if amount <= zenny 0x80144F4C: zenny -= amount, return true; the shop overlay instead subtracts inline (store pc 0x801D1E9C, buy.json) and calls the interior 0x80166FD4 after its own check */
#define PSX_FN_Zenny_Sub 0x80166FCCu
#define func_80166FCC Zenny_Sub  /* alias */

/* confirmed: wtrace money.json 2026-09-04: only writer of zenny 0x80144F4C and lifetime total 0x8014502C, +1 per tick x40 from BATL_END 0x801EF824/0x801EF848; ghidra: (amount, skip_total) -> zenny += amount, total += amount if !skip_total, cap 9999999, returns !capped */
#define PSX_FN_Zenny_Add 0x80166FFCu
#define func_80166FFC Zenny_Add  /* alias */

/* confirmed: AbilityList_ForType(index, ability_id, working) -> pointer to one of four 10-slot lists inside a character record: base = 0x80144964 + index*0xA4 (persistent) or 0x80145F00 + index*0x140 (working, when a2 != 0); type = (byte at 0x801CB231 + ability_id*16) & 3 selects +0x5C / +0x66 / +0x70 / +0x7A. Called by AbilityList_Add 0x80165BCC, which then fills the first zero slot of ten. Disassembled 2026-09-05; the card1 saves show the lists populated (Momo +0x5C/+0x66, Teepo +0x70, Rei +0x70/+0x7A) */
#define PSX_FN_AbilityList_ForType 0x80167514u
#define func_80167514 AbilityList_ForType  /* alias */

/* confirmed: BIOS thunk: li t2,0xA0; jr t2; li t1,0x2F = A0:2F rand() (psx-spx), read from the disc EXE 2026-09-05. Result mod 8 indexes the damage-variance tables (0x801D0C7C, 0x801EAF50), &1 the +0/+1 base term, %100 the hit rolls; 30 call sites in BATTLE.EMI#3, 32 in #15. Ghidra needs it marked returning or every caller's decompile truncates here (tools/ghidra/seed_overlay.py) */
#define PSX_FN_Rand 0x8017ED4Cu
#define func_8017ED4C Rand  /* alias */
