#!/usr/bin/env python
"""names/font_small.toml -> src/bof3_small_font.h

One entry per single-byte glyph code (names/font.toml + the kana table in
tools/jptext.py): the (u, v) of the same character in the game's 8 x 8 font,
or 0xFFFF when the small font has no such glyph. The furigana plugin uses it
to re-point a reading glyph's quad (docs/FURIGANA.md "The 8 px font").

    python tools/sync_small_font.py
"""
import os
import sys
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import jptext  # noqa: E402

SRC = os.path.join(ROOT, "names", "font_small.toml")
OUT = os.path.join(ROOT, "src", "bof3_small_font.h")


def main():
    t = tomllib.load(open(SRC, "rb"))
    page_y, pitch = t["page_y"], t["pitch"]
    where = {}
    for r, row in enumerate(t["rows"]):
        for c, ch in enumerate(row):
            if ch != " " and ch not in where:
                where[ch] = (c * pitch, page_y + r * pitch)
    codes = {}
    codes.update(jptext.SINGLE)
    codes.update(jptext.KANA)
    table = [0xFFFF] * 256
    hit = 0
    for code, ch in codes.items():
        if ch in where:
            u, v = where[ch]
            table[code] = (v << 8) | u
            hit += 1
    lines = ["/* AUTO-GENERATED by tools/sync_small_font.py from names/font_small.toml",
             " * -- do not edit. Single-byte glyph code -> (v << 8 | u) of the same kana",
             " * in the 8 x 8 font on the single-byte page; 0xFFFF = no small glyph. */",
             "#ifndef BOF3_SMALL_FONT_H", "#define BOF3_SMALL_FONT_H",
             "#define BOF3_SMALL_PITCH %d" % pitch,
             "static const unsigned short bof3_small_font[256] = {"]
    for i in range(0, 256, 8):
        lines.append("    " + ", ".join("0x%04X" % v for v in table[i:i + 8]) + ",")
    lines += ["};", "#endif", ""]
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print("wrote %s: %d of %d codes have a small glyph; %d small glyphs unmapped: %s"
          % (OUT, hit, len(codes), len(set(where) - set(codes.values())),
             "".join(sorted(set(where) - set(codes.values())))))


if __name__ == "__main__":
    main()
